./bin tests/inputs/input01.txt > tests/outputs/output01.txt
./bin tests/inputs/input02.txt > tests/outputs/output02.txt
./bin tests/inputs/input03.txt > tests/outputs/output03.txt
./bin tests/inputs/input04.txt > tests/outputs/output04.txt
./bin tests/inputs/input05.txt > tests/outputs/output05.txt
./bin tests/inputs/input06.txt > tests/outputs/output06.txt
./bin tests/inputs/input07.txt > tests/outputs/output07.txt
./bin tests/inputs/input08.txt > tests/outputs/output08.txt
./bin tests/inputs/input09.txt > tests/outputs/output09.txt
./bin tests/inputs/input10.txt > tests/outputs/output10.txt